# 1 Загрузка данных

In [1]:
# emp_id | name           | department  | position        | salary  | hire_date   | city           | rating
# 101    | Иванов А.      | dev         | junior          | 80000   | 2023-01-15  | Москва         | 4.2
# 102    | Петрова Б.     | dev         | middle          | 150000  | 2021-06-01  | Москва         | 3.8
# 103    | Сидоров В.     | analytics   | senior          | 200000  | 2019-03-10  | Санкт-Петербург| 4.9
# 104    | Козлова Г.     | dev         | senior          | 220000  | 2018-11-20  | Москва         | 4.5
# 105    | Морозов Д.     | marketing   | middle          | 120000  | 2022-02-28  | Казань         | 3.1
# 106    | Волкова Е.     | analytics   | junior          | 70000   | 2023-09-01  | Санкт-Петербург| 4.7
# 107    | Новиков Ж.     | marketing   | senior          | 180000  | 2020-07-15  | Москва         | 2.9
# 108    | Федорова З.    | dev         | junior          | 85000   | 2023-04-10  | Казань         | 4.0
# 109    | Алексеев И.    | analytics   | middle          | 160000  | 2021-01-20  | Москва         | 3.5
# 110    | Дмитриева К.   | dev         | middle          | 140000  | 2022-08-05  | Санкт-Петербург| 4.3

In [2]:
import pandas as pd
import numpy as np

data = {
    "emp_id": [101,102,103,104,105,106,107,108,109,110],
    "name": [
        "Иванов А.","Петрова Б.","Сидоров В.","Козлова Г.","Морозов Д.",
        "Волкова Е.","Новиков Ж.","Федорова З.","Алексеев И.","Дмитриева К."
    ],
    "department": [
        "dev","dev","analytics","dev","marketing",
        "analytics","marketing","dev","analytics","dev"
    ],
    "position": [
        "junior","middle","senior","senior","middle",
        "junior","senior","junior","middle","middle"
    ],
    "salary": [
        80000,150000,200000,220000,120000,
        70000,180000,85000,160000,140000
    ],
    "hire_date": [
        "2023-01-15","2021-06-01","2019-03-10","2018-11-20","2022-02-28",
        "2023-09-01","2020-07-15","2023-04-10","2021-01-20","2022-08-05"
    ],
    "city": [
        "Москва","Москва","Санкт-Петербург","Москва","Казань",
        "Санкт-Петербург","Москва","Казань","Москва","Санкт-Петербург"
    ],
    "rating": [
        4.2,3.8,4.9,4.5,3.1,
        4.7,2.9,4.0,3.5,4.3
    ]
}

df = pd.DataFrame(data)

# 2 Исследование данных

In [3]:
print("\nОбщая информация о DataFrame:")
display(df)
print(df.info())

Общая информация о DataFrame:

,emp_id,name,department,position,salary,hire_date,city,rating
0,101,Иванов А.,dev,junior,80000,2023-01-15,Москва,4.2
1,102,Петрова Б.,dev,middle,150000,2021-06-01,Москва,3.8
2,103,Сидоров В.,analytics,senior,200000,2019-03-10,Санкт-Петербург,4.9
3,104,Козлова Г.,dev,senior,220000,2018-11-20,Москва,4.5
4,105,Морозов Д.,marketing,middle,120000,2022-02-28,Казань,3.1
5,106,Волкова Е.,analytics,junior,70000,2023-09-01,Санкт-Петербург,4.7
6,107,Новиков Ж.,marketing,senior,180000,2020-07-15,Москва,2.9
7,108,Федорова З.,dev,junior,85000,2023-04-10,Казань,4.0
8,109,Алексеев И.,analytics,middle,160000,2021-01-20,Москва,3.5
9,110,Дмитриева К.,dev,middle,140000,2022-08-05,Санкт-Петербург,4.3

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      10 non-null     int64
 1   name        10 non-null     str
 2   department  10 non-null     str
 3   position    10 non-null     str
 4   salary      10 non-null     int64
 5   hire_date   10 non-null     str
 6   city        10 non-null     str
 7   rating      10 non-null     float64
dtypes: float64(1), int64(2), str(5)
memory usage: 772.0 bytes
None

In [4]:
rows_before = len(df)
print("\nВсего строк в DataFrame:", rows_before)

print("\nПропуски в данных:")
print(df.isnull().sum())

print(f"\nколичество работников в каждом отделе: {df['department'].value_counts()}")

print(f"\n{df['salary'].max()} - максимальная зарплата в данных")
print(f"{df['salary'].min()} - минимальная зарплата в данных")

empty_rows = df[df.isnull().all(axis=1)]
print("\nКоличество пустых строк:", len(empty_rows))

Всего строк в DataFrame: 10

Пропуски в данных:
emp_id        0
name          0
department    0
position      0
salary        0
hire_date     0
city          0
rating        0
dtype: int64

количество работников в каждом отделе: department
dev          5
analytics    3
marketing    2
Name: count, dtype: int64

220000 - максимальная зарплата в данных
70000 - минимальная зарплата в данных

Количество пустых строк: 0

# 3 Очистка данных
#### пункт 2 иследование данных показал, что блок очистки не нужен.

# 4 Расчеты и выводы

## Блок A

In [5]:
# 1. Покажи всех сотрудников из dev с зарплатой выше 100 000
print("\nСотрудники из dev с зарплатой выше 100 000:")
result = df[(df['department'] == 'dev') & (df['salary'] > 100000)]
display(result)

# 2.  Найди сотрудников с рейтингом ниже 3.5 — это кандидаты на performance review
print("\nКандидаты на performance review (рейтинг ниже 3.5):")
candidates = df[df['rating'] < 3.5]
display(candidates)

# 3.  Отсортируй всех по зарплате (убывание), а при равной зарплате — по рейтингу (убывание)
print("\nОтсортированные по зарплате (убывание):")
display(df.sort_values(by=['salary', 'rating'], ascending=[False,False]))

Сотрудники из dev с зарплатой выше 100 000:

,emp_id,name,department,position,salary,hire_date,city,rating
1,102,Петрова Б.,dev,middle,150000,2021-06-01,Москва,3.8
3,104,Козлова Г.,dev,senior,220000,2018-11-20,Москва,4.5
9,110,Дмитриева К.,dev,middle,140000,2022-08-05,Санкт-Петербург,4.3

Кандидаты на performance review (рейтинг ниже 3.5):

   emp_id        name department position  salary   hire_date    city  rating
4     105  Морозов Д.  marketing   middle  120000  2022-02-28  Казань     3.1
6     107  Новиков Ж.  marketing   senior  180000  2020-07-15  Москва     2.9

Отсортированные по зарплате (убывание):

,emp_id,name,department,position,salary,hire_date,city,rating
3,104,Козлова Г.,dev,senior,220000,2018-11-20,Москва,4.5
2,103,Сидоров В.,analytics,senior,200000,2019-03-10,Санкт-Петербург,4.9
6,107,Новиков Ж.,marketing,senior,180000,2020-07-15,Москва,2.9
8,109,Алексеев И.,analytics,middle,160000,2021-01-20,Москва,3.5
1,102,Петрова Б.,dev,middle,150000,2021-06-01,Москва,3.8
9,110,Дмитриева К.,dev,middle,140000,2022-08-05,Санкт-Петербург,4.3
4,105,Морозов Д.,marketing,middle,120000,2022-02-28,Казань,3.1
7,108,Федорова З.,dev,junior,85000,2023-04-10,Казань,4.0
0,101,Иванов А.,dev,junior,80000,2023-01-15,Москва,4.2
5,106,Волкова Е.,analytics,junior,70000,2023-09-01,Санкт-Петербург,4.7

## Блок B

In [6]:
# 4. Средняя зарплата по каждому отделу
print(f"\nСредняя зарплата по каждому отделу: {df.groupby('department')['salary'].mean()}")

# 5. Количество сотрудников по городам
print(f"\nКоличество сотрудников по городам: {df['city'].value_counts()}")

# 6. Для каждого отдела покажи: минимальную, максимальную и среднюю зарплату одним вызовом
print(f"\nминимальная, максимальная и средняя зарплата по отделу: \n{df.groupby('department')['salary'].agg(['min','max','mean'])}")

Средняя зарплата по каждому отделу: department
analytics    143333.333333
dev          135000.000000
marketing    150000.000000
Name: salary, dtype: float64

Количество сотрудников по городам: city
Москва             5
Санкт-Петербург    3
Казань             2
Name: count, dtype: int64

минимальная, максимальная и средняя зарплата по отделу:
               min     max           mean
department
analytics    70000  200000  143333.333333
dev          80000  220000  135000.000000
marketing   120000  180000  150000.000000

## Блок C

In [7]:
display(df)

,emp_id,name,department,position,salary,hire_date,city,rating
0,101,Иванов А.,dev,junior,80000,2023-01-15,Москва,4.2
1,102,Петрова Б.,dev,middle,150000,2021-06-01,Москва,3.8
2,103,Сидоров В.,analytics,senior,200000,2019-03-10,Санкт-Петербург,4.9
3,104,Козлова Г.,dev,senior,220000,2018-11-20,Москва,4.5
4,105,Морозов Д.,marketing,middle,120000,2022-02-28,Казань,3.1
5,106,Волкова Е.,analytics,junior,70000,2023-09-01,Санкт-Петербург,4.7
6,107,Новиков Ж.,marketing,senior,180000,2020-07-15,Москва,2.9
7,108,Федорова З.,dev,junior,85000,2023-04-10,Казань,4.0
8,109,Алексеев И.,analytics,middle,160000,2021-01-20,Москва,3.5
9,110,Дмитриева К.,dev,middle,140000,2022-08-05,Санкт-Петербург,4.3

In [8]:
# 7. Добавь колонку experience_years — сколько полных лет сотрудник работает (от hire_date до сегодня)
df['hire_date'] = pd.to_datetime(df['hire_date'])
df['experience_years'] = (pd.Timestamp.now() - df['hire_date']).dt.days//365
print(f"\nсколько полных лет работает каждый сотрудник: \n{df[['name', 'experience_years']]}")
# 8. Найди самого высокооплачиваемого сотрудника в каждом отделе

print("\nсамый высокооплачиваемый сотрудник в каждом отделе")
top_indices = df.groupby('department')['salary'].idxmax()
top_by_idxmax = df.loc[top_indices]
display(top_by_idxmax)

# 9. Покажи сотрудников, чья зарплата выше средней по их отделу
print("сотрудники, чья зарплата выше средней по их отделу")
avg_salary_by_dept = df.groupby('department')['salary'].transform('mean')
display(df[df['salary'] > avg_salary_by_dept])

сколько полных лет работает каждый сотрудник:
           name  experience_years
0     Иванов А.                 3
1    Петрова Б.                 4
2    Сидоров В.                 7
3    Козлова Г.                 7
4    Морозов Д.                 4
5    Волкова Е.                 2
6    Новиков Ж.                 5
7   Федорова З.                 3
8   Алексеев И.                 5
9  Дмитриева К.                 3

самый высокооплачиваемый сотрудник в каждом отделе

,emp_id,name,department,position,salary,hire_date,city,rating,experience_years
2,103,Сидоров В.,analytics,senior,200000,2019-03-10,Санкт-Петербург,4.9,7
3,104,Козлова Г.,dev,senior,220000,2018-11-20,Москва,4.5,7
6,107,Новиков Ж.,marketing,senior,180000,2020-07-15,Москва,2.9,5

сотрудники, чья зарплата выше средней по их отделу

,emp_id,name,department,position,salary,hire_date,city,rating,experience_years
1,102,Петрова Б.,dev,middle,150000,2021-06-01,Москва,3.8,4
2,103,Сидоров В.,analytics,senior,200000,2019-03-10,Санкт-Петербург,4.9,7
3,104,Козлова Г.,dev,senior,220000,2018-11-20,Москва,4.5,7
6,107,Новиков Ж.,marketing,senior,180000,2020-07-15,Москва,2.9,5
8,109,Алексеев И.,analytics,middle,160000,2021-01-20,Москва,3.5,5
9,110,Дмитриева К.,dev,middle,140000,2022-08-05,Санкт-Петербург,4.3,3

# Анализ

In [9]:
junior_high_earners = df[(df['position'] == 'junior') & (df['salary'] > avg_salary_by_dept)]
print("\njunior сотрудники с зарплатой выше средней по отделу:")
print(junior_high_earners.shape[0]) # таких нет
display(junior_high_earners[['name', 'department', 'position', 'salary']])

middle_high_earners = df[(df['position'] == 'middle') & (df['salary'] > avg_salary_by_dept)]
print("\nmiddle сотрудники с зарплатой выше средней по отделу:")
print(middle_high_earners.shape[0]) 
display(middle_high_earners[['name', 'department', 'position', 'salary']])

senior_high_earners = df[(df['position'] == 'senior') & (df['salary'] > avg_salary_by_dept)]
print("\nsenior сотрудники с зарплатой выше средней по отделу:")  
print(senior_high_earners.shape[0])
display(senior_high_earners[['name', 'department', 'position', 'salary']])

junior сотрудники с зарплатой выше средней по отделу:
0

Empty DataFrame
Columns: [name, department, position, salary]
Index: []

middle сотрудники с зарплатой выше средней по отделу:
3

           name department position  salary
1    Петрова Б.        dev   middle  150000
8   Алексеев И.  analytics   middle  160000
9  Дмитриева К.        dev   middle  140000

senior сотрудники с зарплатой выше средней по отделу:
3

         name department position  salary
2  Сидоров В.  analytics   senior  200000
3  Козлова Г.        dev   senior  220000
6  Новиков Ж.  marketing   senior  180000

In [10]:
display(df[(df['position'] == 'senior') & (df['rating'] < 3.5)])
#неприемлимый результат, так как senior с рейтингом ниже 3.5 - это кандидаты на performance review
#и зарплата у senior Новикова Ж. из marketinga - 180000, что выше средней по отделу маркетинга (150000), нужно проводить performance review

,emp_id,name,department,position,salary,hire_date,city,rating,experience_years
6,107,Новиков Ж.,marketing,senior,180000,2020-07-15,Москва,2.9,5