In [1]:
#Таблица 1 - студенты

# student_id | name            | city           | signup_date
# S-001      | Алексей К.      | Москва         | 2024-01-10
# S-002      | Мария В.        | Санкт-Петербург| 2024-01-15
# S-003      | Дмитрий Н.      | Казань         | 2024-02-01
# S-004      | Елена Р.        | Москва         | 2024-02-20
# S-005      | Ольга С.        | Новосибирск    | 2024-03-05
# S-006      | Игорь Т.        | Москва         | 2024-03-10

In [2]:
#Таблица 2 — курсы

# course_id | course_name     | price   | category
# PY-101    | Python Basic    | 15000   | programming
# PY-201    | Python Advanced | 25000   | programming
# DA-101    | Data Analysis   | 20000   | analytics
# ML-101    | Machine Learning| 35000   | analytics
# EN-101    | English B2      | 12000   | languages

In [3]:
#Таблица 3 — покупки

# purchase_id | student_id | course_id | purchase_date | status
# 1           | S-001      | PY-101    | 2024-01-15    | completed
# 2           | S-001      | DA-101    | 2024-02-10    | completed
# 3           | S-002      | PY-101    | 2024-01-20    | refunded
# 4           | S-003      | ML-101    | 2024-02-05    | completed
# 5           | S-004      | PY-201    | 2024-02-25    | completed
# 6           | S-004      | EN-101    | 2024-03-01    | completed
# 7           | S-002      | PY-201    | 2024-03-10    | completed
# 8           | S-003      | DA-101    | 2024-03-15    | refunded
# 9           | S-007      | PY-101    | 2024-03-20    | completed

# 1 Загрузка данных

In [4]:
import pandas as pd
import numpy as np

# Создание DataFrame для студентов
students_data = {
    'student_id': ['S-001', 'S-002', 'S-003', 'S-004', 'S-005', 'S-006'],
    'name': ['Алексей К.', 'Мария В.', 'Дмитрий Н.', 'Елена Р.', 'Ольга С.', 'Игорь Т.'],
    'city': ['Москва', 'Санкт-Петербург', 'Казань', 'Москва', 'Новосибирск', 'Москва'],
    'signup_date': ['2024-01-10', '2024-01-15', '2024-02-01', '2024-02-20', '2024-03-05', '2024-03-10']
}

students_df = pd.DataFrame(students_data)
display(students_df)

# Создание DataFrame для курсов
courses_data = {
    'course_id': ['PY-101', 'PY-201', 'DA-101', 'ML-101', 'EN-101'],
    'course_name': ['Python Basic', 'Python Advanced', 'Data Analysis', 'Machine Learning', 'English B2'],
    'price': [15000, 25000, 20000, 35000, 12000],
    'category': ['programming', 'programming', 'analytics', 'analytics', 'languages']
}

courses_df = pd.DataFrame(courses_data)
display(courses_df)

# Создание DataFrame для покупок
purchases_data = {
    'purchase_id': [1, 2, 3, 4, 5, 6, 7, 8, 9],
    'student_id': ['S-001', 'S-001', 'S-002', 'S-003', 'S-004', 'S-004', 'S-002', 'S-003', 'S-007'],
    'course_id': ['PY-101', 'DA-101', 'PY-101', 'ML-101', 'PY-201', 'EN-101', 'PY-201', 'DA-101', 'PY-101'],
    'purchase_date': ['2024-01-15', '2024-02-10', '2024-01-20', '2024-02-05', '2024-02-25', '2024-03-01', '2024-03-10', '2024-03-15', '2024-03-20'],
    'status': ['completed', 'completed', 'refunded', 'completed', 'completed', 'completed', 'completed', 'refunded', 'completed']
}

purchases_df = pd.DataFrame(purchases_data)
display(purchases_df)

  student_id        name             city signup_date
0      S-001  Алексей К.           Москва  2024-01-10
1      S-002    Мария В.  Санкт-Петербург  2024-01-15
2      S-003  Дмитрий Н.           Казань  2024-02-01
3      S-004    Елена Р.           Москва  2024-02-20
4      S-005    Ольга С.      Новосибирск  2024-03-05
5      S-006    Игорь Т.           Москва  2024-03-10

  course_id       course_name  price     category
0    PY-101      Python Basic  15000  programming
1    PY-201   Python Advanced  25000  programming
2    DA-101     Data Analysis  20000    analytics
3    ML-101  Machine Learning  35000    analytics
4    EN-101        English B2  12000    languages

   purchase_id student_id course_id purchase_date     status
0            1      S-001    PY-101    2024-01-15  completed
1            2      S-001    DA-101    2024-02-10  completed
2            3      S-002    PY-101    2024-01-20   refunded
3            4      S-003    ML-101    2024-02-05  completed
4            5      S-004    PY-201    2024-02-25  completed
5            6      S-004    EN-101    2024-03-01  completed
6            7      S-002    PY-201    2024-03-10  completed
7            8      S-003    DA-101    2024-03-15   refunded
8            9      S-007    PY-101    2024-03-20  completed

# 2 Анализ данных

In [14]:
print("\nИнформация о Таблице 1 студенты:\n")
print(students_df.info())
print(students_df.isna().sum())
print(students_df.duplicated().sum()) # в таблице 1 нет дубликатов

Информация о Таблице 1 студенты:

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   6 non-null      str
 1   name         6 non-null      str
 2   city         6 non-null      str
 3   signup_date  6 non-null      str
dtypes: str(4)
memory usage: 324.0 bytes
None
student_id     0
name           0
city           0
signup_date    0
dtype: int64
0

In [ ]:
print("\nИнформация о Таблице 2 курсы\n")
print(courses_df.info())
print(courses_df.isna().sum())
print(courses_df.duplicated().sum()) # в таблице 2 нет дубликатов

Информация о Таблице 2 курсы

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   course_id    5 non-null      str
 1   course_name  5 non-null      str
 2   price        5 non-null      int64
 3   category     5 non-null      str
dtypes: int64(1), str(3)
memory usage: 292.0 bytes
None
course_id      0
course_name    0
price          0
category       0
dtype: int64
0

In [ ]:
print("\nИнформация о Таблице 3 покупки:\n")
print(purchases_df.info())
print(purchases_df.isna().sum())
print(purchases_df.duplicated().sum()) # в таблице 3 нет дубликатов

Информация о Таблице 3 покупки:

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   purchase_id    9 non-null      int64
 1   student_id     9 non-null      str
 2   course_id      9 non-null      str
 3   purchase_date  9 non-null      str
 4   status         9 non-null      str
dtypes: int64(1), str(4)
memory usage: 492.0 bytes
None
purchase_id      0
student_id       0
course_id        0
purchase_date    0
status           0
dtype: int64
0

# 3 Очистка данных

# 4 Рассчеты и выводы